version: "3"

services:
  api:
    build: .
    container_name: anime-cache
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis-cache
    depends_on:
      - redis-cache
  redis-cache:
    image: redis
    container_name: redis-cache
